apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-install
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  project: default
  source:
    path: argocd-managed/tekton-install
    repoURL: https://github.com/enrico2828/pipeline-config-petclinic.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true