apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-tasks
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-managed/tekton-tasks
    repoURL: https://github.com/marleinevankampen/pipeline-config-petclinic.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true