apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app-loader
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-apps
    repoURL: https://github.com/marleinevankampen/pipeline-config-petclinic.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

