apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: petclinic-pipeline
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  workspaces:
    - name: pipeline-ws
    - name: argo-app-ws
    - name: git-app-config-ssh-creds
  params:
    - name: buildnumber
      type: string
      description: A uniqe string that identifies the build
    - name: GIT_USER_NAME
      type: string
      description: |
        Git user name for performing git operation.
      default: "Tekton CI"
    - name: GIT_USER_EMAIL
      type: string
      description: |
        Git user email for performing git operation.
      default: "tekton@devnull.com"
    - name: GIT_REPO_URL_SOURCES
      type: string
      description: |
        Git repostiory that contains the sources of the app.
      default: "https://github.com/marleinevankampen/spring-petclinic.git"
    - name: GIT_REPO_URL_ARGO_CONFIG
      type: string
      description: |
        Git repostiory that contains the ArgoCD app definitions.
      default: "git@github.com:marleinevankampen/pipeline-config-petclinic.git"
    - name: ARGO_APP_FILEPATH
      type: string
      description: |
        The Path to the ArgoCD app relative to the workspace
      default: "argocd-apps"
    - name: ARGO_APP_FILENAME_STAGING
      type: string
      description: |
        The name of the yaml file of the ArgoCD app for staging.
      default: "petclinic-staging.yaml"
    - name: ARGO_APP_FILENAME_PRODUCTION
      type: string
      description: |
        The name of the yaml file of the ArgoCD app for production.
      default: "petclinic-production.yaml"
    - name: PETCLINIC_URL_STAGING
      type: string
      description: |
        The url of the petclinig app for staging.
      default: "http://petclinic-staging.127.0.0.1.nip.io"
    - name: PETCLINIC_URL_PRODUCTION
      type: string
      description: |
        The url of the petclinig app for production.
      default: "http://petclinic-production.127.0.0.1.nip.io"
    - name: PETCLINIC_IMAGE_REPO
      type: string
      description: |
        The repository for the petclinic container image.
      default: "host.k3d.internal:47009/petclinic"

  tasks:
    - name: git-clone-app
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.GIT_REPO_URL_SOURCES)
        - name: revision
          value: main
      workspaces:
        - name: output
          workspace: pipeline-ws
    - name: build-maven
      taskRef:
        name: maven
      runAfter:
        - git-clone-app
      params:
        - name: MAVEN_IMAGE
          value: maven:3.8-adoptopenjdk-8
      workspaces:
        - name: source
          workspace: pipeline-ws
    - name: build-image
      taskRef:
        name: buildah
      runAfter:
        - build-maven
      params:
        - name: IMAGE
          value: $(params.PETCLINIC_IMAGE_REPO):$(tasks.build-maven.results.mvn-version)-$(params.buildnumber)
        - name: TLSVERIFY
          value: 'false'
      workspaces:
        - name: source
          workspace: pipeline-ws
    - name: git-clone-app-config
      taskRef:
        name: git-clone
      runAfter:
        - build-image
      params:
        - name: url
          value: $(params.GIT_REPO_URL_ARGO_CONFIG)
        - name: revision
          value: main
      workspaces:
        - name: output
          workspace: argo-app-ws
        - name: ssh-directory
          workspace: git-app-config-ssh-creds
    - name: update-petclinic-staging
      taskRef:
        name: update-argocd-app
      runAfter:
        - git-clone-app-config
      params:
        - name: ARGO_APP_FILEPATH
          value: $(params.ARGO_APP_FILEPATH)
        - name: ARGO_APP_FILENAME
          value: $(params.ARGO_APP_FILENAME_STAGING)
        - name: ARGO_APP_IMAGE_TAG
          value: $(tasks.build-maven.results.mvn-version)-$(params.buildnumber)
      workspaces:
        - name: source
          workspace: argo-app-ws
    - name: commit-petclinic-staging
      taskRef:
        name: git-cli
      runAfter:
        - update-petclinic-staging
      params:
        - name: GIT_USER_NAME
          value: $(params.GIT_USER_NAME)
        - name: GIT_USER_EMAIL
          value: $(params.GIT_USER_EMAIL)
        - name: GIT_SCRIPT
          value: |
            git checkout main
            git pull origin main
            git add $(params.ARGO_APP_FILEPATH)/$(params.ARGO_APP_FILENAME_STAGING)
            git commit -m "Tekton pipeline updated petclinic-staging to $(tasks.build-maven.results.mvn-version)-$(params.buildnumber)"
            git pull origin main
            git push origin
      workspaces:
        - name: source
          workspace: argo-app-ws
        - name: ssh-directory
          workspace: git-app-config-ssh-creds
    - name: verify-app-staging
      taskRef:
        name: verify-argocd-app
      runAfter:
        - commit-petclinic-staging
      retries: 15
      params:
        - name: ARGO_APP_IMAGE_TAG
          value: $(tasks.build-maven.results.mvn-version)-$(params.buildnumber)
        - name: ARGO_APP_NAME
          value: petclinic-staging
    - name: smoke-test-staging
      taskRef:
        name: smoke-test
      runAfter:
        - verify-app-staging
      retries: 3
      params:
        - name: SMOKE_SCRIPT
          value: |
            BASE_URL="$(params.PETCLINIC_URL_STAGING)"

            smoke_url_ok "$BASE_URL"
                smoke_assert_body "Welcome"
                smoke_assert_headers "text/html;charset=UTF-8"

            smoke_url_ok "$BASE_URL/owners?lastName=Davis"
                smoke_assert_body "638 Cardinal Ave."
                smoke_assert_body "6085553198"
    - name: update-petclinic-production
      taskRef:
        name: update-argocd-app
      runAfter:
        - smoke-test-staging
      params:
        - name: ARGO_APP_FILEPATH
          value: $(params.ARGO_APP_FILEPATH)
        - name: ARGO_APP_FILENAME
          value: $(params.ARGO_APP_FILENAME_PRODUCTION)
        - name: ARGO_APP_IMAGE_TAG
          value: $(tasks.build-maven.results.mvn-version)-$(params.buildnumber)
      workspaces:
        - name: source
          workspace: argo-app-ws
    - name: commit-petclinic-production
      taskRef:
        name: git-cli
      runAfter:
        - update-petclinic-production
      params:
        - name: GIT_USER_NAME
          value: $(params.GIT_USER_NAME)
        - name: GIT_USER_EMAIL
          value: $(params.GIT_USER_EMAIL)
        - name: GIT_SCRIPT
          value: |
            git checkout main
            git pull origin main
            git add $(params.ARGO_APP_FILEPATH)/$(params.ARGO_APP_FILENAME_PRODUCTION)
            git commit -m "Tekton pipeline updated petclinic-production to $(tasks.build-maven.results.mvn-version)-$(params.buildnumber)"
            git pull origin main
            git push origin
      workspaces:
        - name: source
          workspace: argo-app-ws
        - name: ssh-directory
          workspace: git-app-config-ssh-creds
    - name: verify-app-production
      taskRef:
        name: verify-argocd-app
      runAfter:
        - commit-petclinic-production
      retries: 15
      params:
        - name: ARGO_APP_IMAGE_TAG
          value: $(tasks.build-maven.results.mvn-version)-$(params.buildnumber)
        - name: ARGO_APP_NAME
          value: petclinic-production
    - name: smoke-test-production
      taskRef:
        name: smoke-test
      runAfter:
        - verify-app-production
      retries: 3
      params:
        - name: SMOKE_SCRIPT
          value: |
            BASE_URL="$(params.PETCLINIC_URL_PRODUCTION)"

            smoke_url_ok "$BASE_URL"
                smoke_assert_body "Welcome"
                smoke_assert_headers "text/html;charset=UTF-8"

            smoke_url_ok "$BASE_URL/owners?lastName=Davis"
                smoke_assert_body "638 Cardinal Ave."
                smoke_assert_body "6085553198"
